all:
	gcc -g -o output_assignment_2_1 1.c
	gcc -g -o output_assignment_2_2a 2a.c
	gcc -g -o output_assignment_2_2b 2b.c
	gcc -g -o output_assignment_2_2c 2c.c
	gcc -g -o output_assignment_2_3 3.c
	gcc -g -o output_assignment_2_5 5.c

Q1:
	gcc -g -o output_assignment_2_1 1.c

Q2a:
	gcc -g -o output_assignment_2_2a 2a.c

Q2b:
	gcc -g -o output_assignment_2_2b 2b.c

Q2c:
	gcc -g -o output_assignment_2_2c 2c.c

Q3:
	gcc -g -o output_assignment_2_3 3.c

Q5:
	gcc -g -o output_assignment_2_5 5.c

