all:

	gcc -g -o output_assignment_1_1 1.c
	# gcc -g -o output_assignment_1_2 2.c
	gcc -g -o output_assignment_1_3 3.c
	gcc -g -o output_assignment_1_4 4.c
	gcc -g -o output_assignment_1_5 5.c

Q1:

	gcc -g -o output_assignment_1_1 1.c

# Q2:

# 	gcc -g -o output_assignment_1_2 2.c

Q3:

	gcc -g -o output_assignment_1_3 3.c

Q4:

	gcc -g -o output_assignment_1_4 4.c

Q5:
	gcc -g -o output_assignment_1_5 5.c

