all:
	gcc -g -o output_assignment_3_3a 3a.c
	gcc -g -o output_assignment_3_3b 3b.c
	gcc -g -o output_assignment_3_4 4.c

Q3a:
	gcc -g -o output_assignment_3_3a 3a.c

Q3b:
	gcc -g -o output_assignment_3_3b 3b.c

Q4:
	gcc -g -o output_assignment_3_4 4.c

